package se.sundsvall.casedata.api.model.validation.enums;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.EnumSet;
import java.util.List;
import lombok.Getter;

@Getter
@Schema(example = "PARKING_PERMIT")
public enum CaseType {

	// PARKINGPERMIT
	PARKING_PERMIT,
	PARKING_PERMIT_RENEWAL,
	LOST_PARKING_PERMIT,

	// Färdtjänst
	// Ansökan av färdtjänst
	PARATRANSIT,
	// Ansökan om fortsatt färdtjänst
	PARATRANSIT_RENEWAL,
	// Ansökan om förändring av insatser
	PARATRANSIT_CHANGE,
	// Ansökan om riksfärdtjänst
	PARATRANSIT_NATIONAL,
	// Ansökan om fortsatt riksfärdtjänst
	PARATRANSIT_NATIONAL_RENEWAL,
	// Ansökan om RIAK
	PARATRANSIT_RIAK,
	// Ansökan om busskort
	PARATRANSIT_BUS_CARD,
	// Anmälan av färdtjänst
	PARATRANSIT_NOTIFICATION,
	// Anmälan om förändring av insatser
	PARATRANSIT_NOTIFICATION_CHANGE,
	// Anmälan om fortsatt färdtjänst
	PARATRANSIT_NOTIFICATION_RENEWAL,
	// Anmälan om riksfärdtjänst
	PARATRANSIT_NOTIFICATION_NATIONAL,
	// Anmälan om fortsatt riksfärdtjänst
	PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL,
	// Anmälan om RIAK
	PARATRANSIT_NOTIFICATION_RIAK,
	// Anmälan om busskort
	PARATRANSIT_NOTIFICATION_BUS_CARD,

	// MEX
	MEX_LEASE_REQUEST,
	MEX_BUY_LAND_FROM_THE_MUNICIPALITY,
	MEX_SELL_LAND_TO_THE_MUNICIPALITY,
	MEX_SQUARE_PLACE,
	MEX_BUY_SMALL_HOUSE_PLOT,
	MEX_APPLICATION_FOR_ROAD_ALLOWANCE,
	MEX_UNAUTHORIZED_RESIDENCE,
	MEX_LAND_RIGHT,
	MEX_EARLY_DIALOG_PLAN_NOTIFICATION,
	MEX_PROTECTIVE_HUNTING,
	MEX_LAND_INSTRUCTION,
	MEX_OTHER,
	MEX_LAND_SURVEYING_OFFICE,
	MEX_REFERRAL_BUILDING_PERMIT_EARLY_DIALOGUE_PLANNING_NOTICE,
	MEX_INVOICE,
	MEX_REQUEST_FOR_PUBLIC_DOCUMENT,
	MEX_TERMINATION_OF_LEASE,
	MEX_HUNTING_LEASE,
	MEX_FORWARDED_FROM_CONTACTSUNDSVALL,
	MEX_BUILDING_PERMIT,
	MEX_STORMWATER,
	MEX_INVASIVE_SPECIES,
	MEX_LAND_USE_AGREEMENT_VALUATION_PROTOCOL,
	MEX_LITTERING,
	MEX_REFERRAL_CONSULTATION,
	MEX_PUBLIC_SPACE_LEASE,
	MEX_EASEMENT,
	MEX_TREES_FORESTS,
	MEX_ROAD_ASSOCIATION,
	MEX_RETURNED_TO_CONTACT_SUNDSVALL,
	MEX_SMALL_BOAT_HARBOR_DOCK_PORT,
	MEX_SELL_LAND_TO_THE_MUNICIPALITY_PRIVATE,
	MEX_SELL_LAND_TO_THE_MUNICIPALITY_BUSINESS,
	// GENERAL
	APPEAL;

	public static List<CaseType> getMexCaseTypes() {
		return List.copyOf(EnumSet.of(
			MEX_LEASE_REQUEST,
			MEX_BUY_LAND_FROM_THE_MUNICIPALITY,
			MEX_SELL_LAND_TO_THE_MUNICIPALITY,
			MEX_SQUARE_PLACE,
			MEX_BUY_SMALL_HOUSE_PLOT,
			MEX_APPLICATION_FOR_ROAD_ALLOWANCE,
			MEX_UNAUTHORIZED_RESIDENCE,
			MEX_LAND_RIGHT,
			MEX_EARLY_DIALOG_PLAN_NOTIFICATION,
			MEX_PROTECTIVE_HUNTING,
			MEX_LAND_INSTRUCTION,
			MEX_OTHER,
			MEX_LAND_SURVEYING_OFFICE,
			MEX_REFERRAL_BUILDING_PERMIT_EARLY_DIALOGUE_PLANNING_NOTICE,
			MEX_INVOICE,
			MEX_REQUEST_FOR_PUBLIC_DOCUMENT,
			MEX_TERMINATION_OF_LEASE,
			MEX_HUNTING_LEASE,
			MEX_FORWARDED_FROM_CONTACTSUNDSVALL, MEX_BUILDING_PERMIT,
			MEX_STORMWATER,
			MEX_INVASIVE_SPECIES,
			MEX_LAND_USE_AGREEMENT_VALUATION_PROTOCOL,
			MEX_LITTERING,
			MEX_REFERRAL_CONSULTATION,
			MEX_PUBLIC_SPACE_LEASE,
			MEX_EASEMENT,
			MEX_TREES_FORESTS,
			MEX_ROAD_ASSOCIATION,
			MEX_RETURNED_TO_CONTACT_SUNDSVALL,
			MEX_SMALL_BOAT_HARBOR_DOCK_PORT,
			MEX_SELL_LAND_TO_THE_MUNICIPALITY_PRIVATE,
			MEX_SELL_LAND_TO_THE_MUNICIPALITY_BUSINESS));
	}

	public static List<CaseType> getParkingPermitCaseTypes() {
		return List.copyOf(EnumSet.of(
			PARKING_PERMIT,
			PARKING_PERMIT_RENEWAL,
			LOST_PARKING_PERMIT,
			APPEAL,
			PARATRANSIT,
			PARATRANSIT_RENEWAL,
			PARATRANSIT_CHANGE,
			PARATRANSIT_NATIONAL,
			PARATRANSIT_NATIONAL_RENEWAL,
			PARATRANSIT_RIAK,
			PARATRANSIT_BUS_CARD,
			PARATRANSIT_NOTIFICATION,
			PARATRANSIT_NOTIFICATION_CHANGE,
			PARATRANSIT_NOTIFICATION_RENEWAL,
			PARATRANSIT_NOTIFICATION_NATIONAL,
			PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL,
			PARATRANSIT_NOTIFICATION_RIAK,
			PARATRANSIT_NOTIFICATION_BUS_CARD));
	}
}
