package se.sundsvall.casedata.api.model.validation.enums;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
@Schema(example = "PARKING_PERMIT")
public enum CaseType {

	// BYGGR
	NYBYGGNAD_ANSOKAN_OM_BYGGLOV("BUILD"),
	ANMALAN_ATTEFALL("BUILD"),
	// ECOS
	REGISTRERING_AV_LIVSMEDEL("ENV"),
	ANMALAN_INSTALLATION_VARMEPUMP("ENV"),
	ANSOKAN_TILLSTAND_VARMEPUMP("ENV"),
	ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP("ENV"),
	ANMALAN_INSTALLATION_ENSKILT_AVLOPP_UTAN_WC("ENV"),
	ANMALAN_ANDRING_AVLOPPSANLAGGNING("ENV"),
	ANMALAN_ANDRING_AVLOPPSANORDNING("ENV"),
	ANMALAN_HALSOSKYDDSVERKSAMHET("ENV"),
	// PARKINGPERMIT
	PARKING_PERMIT("PRH"),
	PARKING_PERMIT_RENEWAL("PRH"),
	LOST_PARKING_PERMIT("PRH"),
	// MEX
	MEX_LEASE_REQUEST("MEX"),
	MEX_BUY_LAND_FROM_THE_MUNICIPALITY("MEX"),
	MEX_SELL_LAND_TO_THE_MUNICIPALITY("MEX"),
	MEX_APPLICATION_SQUARE_PLACE("MEX"),
	MEX_BUY_SMALL_HOUSE_PLOT("MEX"),
	MEX_APPLICATION_FOR_ROAD_ALLOWANCE("MEX"),
	MEX_UNAUTHORIZED_RESIDENCE("MEX"),
	MEX_LAND_RIGHT("MEX"),
	MEX_EARLY_DIALOG_PLAN_NOTIFICATION("MEX"),
	MEX_PROTECTIVE_HUNTING("MEX"),
	MEX_LAND_INSTRUCTION("MEX"),
	MEX_OTHER("MEX"),
	MEX_LAND_SURVEYING_OFFICE("MEX"),
	MEX_REFERRAL_BUILDING_PERMIT_EARLY_DIALOUGE_PLANNING_NOTICE("MEX"),
	MEX_INVOICE("MEX"),
	MEX_REQUEST_FOR_PUBLIC_DOCUMENT("MEX"),
	MEX_TERMINATION_OF_LEASE("MEX"),
	MEX_TERMINATION_OF_HUNTING_LEASE("MEX"),
	MEX_FORWARDED_FROM_CONTACTSUNDSVALL("MEX"),
	APPEAL("O");

	private final String abbreviation;

	CaseType(final String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public static List<CaseType> getValuesByAbbreviation(final String abbreviation) {
		return Arrays.stream(values()).filter(caseType -> caseType.getAbbreviation().equals(abbreviation)).toList();
	}
}
