spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///ittest
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

#----------------------------------------
# Integration settings
#----------------------------------------
integration:
  parkingpermit:
    supported-namespaces:
      - MY_NAMESPACE
      - SBK_PARKING_PERMIT
  landandexploitation:
    supported-namespaces:
      - SBK_MEX
config:
  parkingpermit:
    base-url: http://localhost:${wiremock.server.port:}/parkingpermit
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  landandexploitation:
    base-url: http://localhost:${wiremock.server.port:}/landandexploitation
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  web-message-collector:
    base-url: http://localhost:${wiremock.server.port:}/webmessagecollector
    client-id: client-id
    client-secret: client-secret
    token-url: http://localhost:${wiremock.server.port:}/token
  email-reader:
    base-url: http://localhost:${wiremock.server.port:}/emailreader
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  employee:
    base-url: http://localhost:${wiremock.server.port:}/employee
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  message-exchange:
    base-url: http://localhost:${wiremock.server.port:}/message-exchange
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  messaging:
    base-url: http://localhost:${wiremock.server.port:}/messaging
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  messaging-settings:
    base-url: http://localhost:${wiremock.server.port:}/messaging-settings
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  relation:
    base-url: http://localhost:${wiremock.server.port:}/relation
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret
  paratransit:
    base-url: http://localhost:${wiremock.server.port:}/paratransit
    token-url: http://localhost:${wiremock.server.port:}/token
    client-id: client-id
    client-secret: client-secret

#----------------------------------------
# Scheduler settings
#----------------------------------------
scheduler:
  message-collector:
    enabled: false
  emailreader:
    enabled: false
  suspension:
    enabled: false
  notification:
    enabled: false
  messageexchange:
    enabled: false

#----------------------------------------
# Retry settings
#----------------------------------------
resilience4j:
  retry:
    instances:
      parkingpermit:
        max-attempts: 1
