ALTER TABLE message
    MODIFY COLUMN direction ENUM('INBOUND', 'OUTBOUND');

ALTER TABLE message
    MODIFY COLUMN message_type ENUM('SMS', 'EMAIL');

ALTER TABLE decision
    MODIFY COLUMN decision_type ENUM('RECOMMENDED', 'PROPOSED', 'FINAL');

ALTER TABLE decision
    MODIFY COLUMN decision_outcome ENUM('APPROVAL', 'REJECTION', 'DISMISSAL', 'CANCELLATION');

ALTER TABLE facility
    MODIFY COLUMN address_category ENUM('POSTAL_ADDRESS', 'INVOICE_ADDRESS', 'VISITING_ADDRESS');

ALTER TABLE stakeholder
    MODIFY COLUMN type ENUM('PERSON','ORGANIZATION');

ALTER TABLE stakeholder_addresses
    MODIFY COLUMN address_category ENUM('POSTAL_ADDRESS','INVOICE_ADDRESS','VISITING_ADDRESS');

ALTER TABLE stakeholder_contact_information
    MODIFY COLUMN contact_type ENUM('CELLPHONE','PHONE','EMAIL');

ALTER TABLE stakeholder_roles
    MODIFY COLUMN roles ENUM('CONTROL_OFFICIAL', 'APPLICANT', 'PROPERTY_OWNER', 'PAYMENT_PERSON',
    'INVOICE_RECIPENT', 'OPERATOR', 'CONTACT_PERSON', 'ADMINISTRATOR', 'FELLOW_APPLICANT','DRIVER',
    'PASSENGER', 'DOCTOR');

ALTER TABLE errand
    MODIFY COLUMN channel ENUM('ESERVICE', 'EMAIL', 'WEB_UI');

ALTER TABLE errand
    MODIFY COLUMN priority ENUM('HIGH', 'MEDIUM', 'LOW');

ALTER TABLE errand
    MODIFY COLUMN case_type ENUM(
    'NYBYGGNAD_ANSOKAN_OM_BYGGLOV',
    'ANMALAN_ATTEFALL',
    'REGISTRERING_AV_LIVSMEDEL',
    'ANMALAN_INSTALLATION_VARMEPUMP',
    'ANSOKAN_TILLSTAND_VARMEPUMP',
    'ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP',
    'ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC',
    'ANMALAN_ANDRING_AVLOPPSANLAGGNING',
    'ANMALAN_ANDRING_AVLOPPSANORDNING',
    'ANMALAN_HALSOSKYDDSVERKSAMHET',
    'PARKING_PERMIT',
    'PARKING_PERMIT_RENEWAL',
    'LOST_PARKING_PERMIT');

ALTER TABLE facility
    MODIFY COLUMN facility_type ENUM(
    'ONE_FAMILY_HOUSE',
    'APARTMENT_BLOCK',
    'WEEKEND_COTTAGE',
    'OFFICE_BUILDING',
    'INDUSTRIAL_BUILDING',
    'GARAGE',
    'CARPORT',
    'STOREHOUSE',
    'GREENHOUSE',
    'GUEST_HOUSE',
    'WAREHOUSE',
    'WORKSHOP_BUILDING',
    'RESTAURANT',
    'SCHOOL',
    'PRESCHOOL',
    'PARKING',
    'DEPOT',
    'MARINA',
    'WALL',
    'PALING',
    'RECYCLING_STATION',
    'OTHER',
    'FURNISHING_OF_ADDITIONAL_DWELLING',
    'ANCILLARY_BUILDING',
    'ANCILLARY_HOUSING_BUILDING',
    'DORMER',
    'EXTENSION');


ALTER TABLE attachment
    MODIFY COLUMN category ENUM(
    'ARIT',
    'FAS',
    'FS2',
    'FAP',
    'FAPL',
    'FPSS',
    'FS',
    'FASSIT',
    'FAS2',
    'FASSIT2',
    'FOTOMON',
    'FÄRG',
    'MAST',
    'MUR',
    'MÅTT',
    'PERSPEKTIV',
    'PLA',
    'PLFA',
    'PLFASE',
    'PLFASESI',
    'PLFASI',
    'PLFA2',
    'PFSI2',
    'PLSE2',
    'PSS2',
    'PLSE',
    'PSS',
    'PLASIT',
    'PFS2',
    'PFSS2',
    'TEVS',
    'UPLA',
    'PLAN',
    'PLANK',
    'PLA2',
    'PSI2',
    'REL',
    'REVRIT',
    'RITNING',
    'TJ',
    'RIT',
    'SEK',
    'SEKSIT',
    'SEKT',
    'SEK2',
    'SESI2',
    'SKYL',
    'UPPM',
    'ANV',
    'ANM',
    'ANMÄ',
    'ANS',
    'ANSFÖ',
    'ANSM',
    'ANSR',
    'ANSS',
    'BEGLST',
    'BERBSA',
    'BLST',
    'OMPLÄ',
    'BULL',
    'DEB',
    'DEL',
    'DELK',
    'DELSLU',
    'DELSTA',
    'DOM',
    'ENER',
    'ENEDEK',
    'FAST',
    'FÖLJREVRIT',
    'FÖRG2',
    'GODFÄ',
    'GRAM',
    'INFOSS',
    'INTSLUT',
    'KM',
    'MOTBKR',
    'OVK',
    'PM',
    'PMINN',
    'PROARB',
    'PROTAU',
    'PROTKS',
    'PROTPLU',
    'PROTSBN',
    'PROSS',
    'PROTS',
    'REMISS',
    'REMS',
    'RÄTT',
    'SKP',
    'SBES',
    'STAB',
    'SVAR',
    'SVAR2år',
    'TJÄ',
    'UNDER',
    'ÄRB',
    'ÖVER',
    'ADRESS',
    'ANSUPA',
    'ANNO',
    'ANSF',
    'ANSSL',
    'ANSUP',
    'ANKVU',
    'ARBI',
    'BEHA',
    'AVPLAN',
    'BANK',
    'BEGSTART',
    'BEK',
    'BEKMOTANS',
    'BEMÖ',
    'BESKA',
    'BESLUT',
    'BIL',
    'BRS',
    'BRAB',
    'BRAD',
    'BROS',
    'DPH',
    'DETALJ',
    'DHBHUR',
    'ELD',
    'EPOS',
    'EXRIT',
    'FAKTU',
    'FAKTUS',
    'FOTO',
    'FUM',
    'FSF',
    'FÖLJ',
    'FÖRB',
    'FÖRK',
    'FÖRR',
    'FÖRGARBO',
    'URÖR',
    'GRA',
    'GRAN',
    'GBLAD',
    'HISSINT',
    'HUR',
    'ARK',
    'INTFAK',
    'INTY',
    'KLA',
    'KOMP',
    'KONT',
    'KPLAN',
    'RAPP',
    'KVAL',
    'LUFT',
    'LUTE',
    'MAIL',
    'MAPL',
    'MATINV',
    'MEDDEL',
    'MIRP',
    'MINN',
    'POIT',
    'PRESENTA',
    'PRES',
    'KPV',
    'PROT',
    'PÅMINNTB',
    'RAP',
    'REMUA',
    'RUE',
    'HBB',
    'RIVA',
    'RIVP',
    'SAK',
    'SAKUT',
    'KPR',
    'KP',
    'KR',
    'SIN',
    'SKR',
    'KA',
    'SKY',
    'SLUT',
    'SCB',
    'STIM',
    'SÅF',
    'TEBY',
    'TEKN',
    'TEKRAP',
    'TILL',
    'TILLVR',
    'SBN',
    'SAKNAS',
    'UND',
    'UKP',
    'UKR',
    'UNDUT',
    'UBGARBO',
    'UTBEU',
    'UTSK',
    'UTSKP',
    'UTSKS',
    'BRAU',
    'UKA',
    'ÅTG',
    'GEO',
    'GRUNDP',
    'GRUNDR',
    'KOND',
    'UKON',
    'KONR',
    'STOMR',
    'TAPL',
    'TSR',
    'KART',
    'NYKA',
    'SITU',
    'TOMTPLBE',
    'VAH',
    'VENT',
    'UVEN',
    'VS',
    'VVSH',
    'ANMALAN_LIVSMEDELSANLAGGNING',
    'ANMALAN_ENSKILT_AVLOPP',
    'ANSOKAN_ENSKILT_AVLOPP',
    'ANMALAN_ANDRING_AVLOPPSANLAGGNING',
    'ANMALAN_ANDRING_AVLOPPSANORDNING',
    'ANMALAN_VARMEPUMP',
    'ANSOKAN_TILLSTAND_VARMEPUMP_MINDRE_AN_100KW',
    'ANMALAN_HALSOSKYDDSVERKSAMHET',
    'SITUATIONSPLAN',
    'SKRIVELSE',
    'MEDICAL_CONFIRMATION',
    'POLICE_REPORT',
    'PASSPORT_PHOTO',
    'SIGNATURE',
    'POWER_OF_ATTORNEY',
    'OTHER',
    'ERRAND_SCANNED_APPLICATION',
    'SERVICE_RECEIPT',
    'OTHER_ATTACHMENT');







