UPDATE errand
SET case_type = 'MEX_HUNTING_LEASE'
WHERE case_type = 'MEX_TERMINATION_OF_HUNTING_LEASE';

UPDATE errand
SET case_type = 'MEX_SQUARE_PLACE'
WHERE case_type = 'MEX_APPLICATION_SQUARE_PLACE';
